### PR TITLE
fix: redcap security

### LINKED ISSUE #37: Address issues from redcap security

### PR DESCRIPTION
**Pull request by mattsliv**
This PR completes the tasks of #37 

Closes #37

### CODE REVIEW

File: js/markerjs2.js [hunk 1]
```diff
@@ -13,4 +13,4 @@
...
-//# sourceMappingURL=markerjs2.js.map
+// sourceMappingURL=markerjs2.js.map
```
Comment (mcmcgrath13) [inline js/markerjs2.js]: do we need this line at all? I don't think we have the source map here

Comment (mattsliv) [reply js/markerjs2.js]: I was not sure since I'm not familiar with it. I removed it and nothing broke so we should be fine.
